### ISSUE TITLE
Not working on 1.21

### ISSUE THREAD

**Issue by LightWilliamz** [girlbossdev/PerspectiveEnhancements#1]
This is a great mod and hope you updated it soon.

**Comment by azurejelly** [comment]
Here's a build that should work properly on 1.21.1:

[perspective-enhancements-1.0.2-1.21.1.zip](https://github.com/user-attachments/files/16748403/perspective-enhancements-1.0.2-1.21.1.zip)

You can also build it yourself if you want to: #2
