### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by seriousfreezing** [girlbossdev/PerspectiveEnhancements#3]
I know I could do two separate issues on this, but let's go:

1. You could release a version 1.21.1 on CurseForge, so it could help a lot to release modpacks with your mod there.

2. Could you add a feature to add third-person aiming?

**Comment by girlbossdev** [comment]
> You could release a version 1.21.1 on CurseForge, so it could help a lot to release modpacks with your mod there.

I'll probably do this at some point, I chose to only release on Modrinth out of personal preference but I'll consider it if people do actually seem to care about my mods.

> Could you add a feature to add third-person aiming?

Could you elaborate on this? I'm assuming you mean freelook, in which case I don't see much of a reason to implement it as there are already existing mods for it. My mod shouldn't conflict with them, though if it somehow does then let me know and I'll try to fix it.

**Comment by seriousfreezing** [comment]
> Could you elaborate on this? I'm assuming you mean freelook, in which case I don't see much of a reason to implement it as there are already existing mods for it. My mod shouldn't conflict with them, though if it somehow does then let me know and I'll try to fix it.

No, it has nothing to do with the freelook. It's about adding the crosshair in the third person. I know it's not a big feature, but for me, who has to have two mods to have these things, having it in your mod would be better, I imagine.

**Comment by girlbossdev** [comment]
I see, my bad then. Still, I'm not really interested in adding features that already exist in other mods as I've said before, but thanks for the suggestion nonetheless.
